# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify container with the desired Node version 
      - image: circleci/node:latest

    working_directory: ~/resume
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
        fingerprints:
           - "7c:80:74:bc:1d:9e:2e:1f:bb:6c:a4:4c:4c:56:0f:36"
      
      - checkout

      # Load cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download dependencies
      - run: yarn install
      
      # Save dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build script
      - run: yarn build

      - deploy: 
        command: |
          git config user.email "iknowsmtp@gmail.com"
          git config user.name "CircleCI Deployment Bot"
          yarn deploy -m "Build \#${CIRCLE_BUILD_NUM} from ${CIRCLE_BUILD_URL}"
