# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify container with the desired Node version 
      - image: circleci/node:latest

    working_directory: ~/resume
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "97:3c:78:0c:4f:cb:1f:64:5e:7d:c8:a7:0f:ff:d6:20"
      
      - checkout

      # Load cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download dependencies
      - run: yarn install
      
      # Save dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build script
      - run: yarn build

      - deploy: 
          command: |
            git config user.email "circleci-deployment-bot@iknowht.ml"
            git config user.name "circleci-deployment-bot"
            yarn deploy -m "Build #${CIRCLE_BUILD_NUM} for commit ${CIRCLE_SHA1} from ${CIRCLE_BUILD_URL} [ci skip]"
